#pragma once

// Application
#define RENDER_OFFLINE 1
#define USE_VSYNC !RENDER_OFFLINE
#define SHOW_FRAMETIMES !RENDER_OFFLINE

#if RENDER_OFFLINE
	#define NUM_SAMPLES_PER_FRAME 1
	#define NUM_FRAMES_TO_RENDER 300
#else
	#define NUM_SAMPLES_PER_FRAME 1
	#define NUM_FRAMES_TO_RENDER 1
#endif

// 1920 = 2 2 2 2 2 2 2 3 5
// 1080 = 2 2 2 3 3 3 5

#define RENDER_BUFFER_PIXEL_HEIGHT 720
#define RENDER_BUFFER_PIXEL_WIDTH  1280

//#define RENDER_BUFFER_PIXEL_HEIGHT 1080
//#define RENDER_BUFFER_PIXEL_WIDTH  1920

//#define RENDER_BUFFER_PIXEL_HEIGHT 2160
//#define RENDER_BUFFER_PIXEL_WIDTH  3840

#define WINDOW_CLIENT_PIXEL_HEIGHT 1080
#define WINDOW_CLIENT_PIXEL_WIDTH  1920

// Rendering
#define USE_ENV_MAP 1
#define OUTPUT_TO_SCREEN !RENDER_OFFLINE
#define USE_NON_TEMPORAL_STORE 1

// Threading / Work Queue
#define NUM_THREADS 8

#define NUM_TILES_X 16
#define NUM_TILES_Y 16

